import Image from "../lib/imports";

export const navLinks = [
  {
    name: "Home",
    path: "/",
  },
  {
    name: "About Us",
    path: "#about-us",
  },
  {
    name: "Members",
    path: "#members",
  },
  {
    name: "Events",
    path: "#events",
  },
  {
    name: "Contact",
    path: "#contact",
  },
];

export const appConfigs = {
  name: "Landzun Development Association",
};

export const impacts = [
  "Local Initiatives",
  "Green Spaces",
  "Education",
  "Volunteering",
  "Cultural Events",
  "Sustainability",
  "Neighborhood Watch",
  "Community Garden",
];

export const grandPatronsOfTheAssociation = [
  {
    src: Image.FormarEmirImage,
    note: "His Royal Highness \n Alh.（Dr）Umaru Sanda Ndayako, CFR  \nEtsu Nupe \n and Chairman, Niger State Council of Traditional Rulers",
    name: "GRAND PATRON (1982 TO 2003)",
  },
  {
    src: Image.EmirImage,
    note: "His Royal Highness \n Alh.（Dr）Yahaya Abubakar, CFR  \nEtsu Nupe \n and Chairman, Niger State Council of Traditional Rulers",
    name: "GRAND PATRON (2003 TO-DATE)",
  },
];

export const members = [
  {
    id: "1",
    name: "Alh Abdullahi A. Adamu",
    image: "/placeholder.svg?height=200&width=200",
    position: "President",
    activeFrom: "1982-1986",
  },
  {
    id: "2",
    name: "Mall Adamu N. Ahmed",
    image: "/placeholder.svg?height=200&width=200",
    position: "1st Vice President",
    activeFrom: "1982-1986",
  },
  {
    id: "3",
    name: "Alh Auda Koloce",
    image: "/placeholder.svg?height=200&width=200",
    position: "2nd Vice President",
    activeFrom: "1982-1986",
  },
  {
    id: "4",
    name: "Mall Salihu Ndagi",
    image: "/placeholder.svg?height=200&width=200",
    position: "Sec Gen",
    activeFrom: "1982-1986",
  },
  {
    id: "5",
    name: "Mall Mohammed B. Shehu",
    image: "/placeholder.svg?height=200&width=200",
    position: "Asst Sec Gen",
    activeFrom: "1982-1986",
  },
  {
    id: "6",
    name: "Dr. Sheikh A. Abdullahi",
    image: "/placeholder.svg?height=200&width=200",
    position: "Treasurer",
    activeFrom: "1982-1986",
  },
  {
    id: "7",
    name: "Mall Sulayman Y. Muhammad",
    image: "/placeholder.svg?height=200&width=200",
    position: "Asst Treasurer",
    activeFrom: "1982-1986",
  },
  {
    id: "8",
    name: "Dr. Usman Nakordi",
    image: "/placeholder.svg?height=200&width=200",
    position: "Sec Special Duties",
    activeFrom: "1982-1986",
  },
  {
    id: "9",
    name: "Majigi Aliyu",
    image: "/placeholder.svg?height=200&width=200",
    position: "Social Sec",
    activeFrom: "1982-1986",
  },
  {
    id: "10",
    name: "Lakpene Yusuf",
    image: "/placeholder.svg?height=200&width=200",
    position: "Legal Advisor",
    activeFrom: "1982-1986",
  },
  {
    id: "11",
    name: "Aminu B. Alhaji",
    image: "/placeholder.svg?height=200&width=200",
    position: "P.R.O",
    activeFrom: "1982-1986",
  },
  {
    id: "12",
    name: "Ishaq Ndaji",
    image: "/placeholder.svg?height=200&width=200",
    position: "Asst P.R.O",
    activeFrom: "1982-1986",
  },
  {
    id: "13",
    name: "Usman B. Ibrahim",
    image: "/placeholder.svg?height=200&width=200",
    position: "Fin Sec",
    activeFrom: "1982-1986",
    phoneNumber: "123-456-7890",
  },
  {
    id: "14",
    name: "Abdulkadir Yamma",
    image: "https://i.ibb.co/XtPzmbR/yanda.jpg",
    position: "Asst Fin Sec",
    activeFrom: "1982-1986",
    email: "abusyaventuresltd@gmail.com",
    phoneNumber: "123-456-7890",
  },
  {
    id: "15",
    name: "Abdullahi N. Aliyu",
    image: "/placeholder.svg?height=200&width=200",
    position: "Ex Official",
    activeFrom: "1982-1986",
    phoneNumber: "123-456-7890",
  },
  {
    id: "16",
    name: "Mohammed A. Shehu",
    image: "/placeholder.svg?height=200&width=200",
    position: "Ex Official",
    activeFrom: "1982-1986",
    phoneNumber: "123-456-7890",
  },
  {
    id: "17",
    name: "Baba Alfa",
    image: "https://i.ibb.co/xHL5yd7/baba-alfa-3.jpg",
    position: "Ex Official",
    activeFrom: "1982-1986",
  },

  //1886-1990
  {
    id: "18",
    name: "Abdullahi N. Aliyu",
    image: "/placeholder.svg?height=200&width=200",
    position: "President",
    activeFrom: "1986-1990",
  },
  {
    id: "19",
    name: "Alhaji Alfa Muhammad",
    image: "/placeholder.svg?height=200&width=200",
    position: "1st Vice President",
    activeFrom: "1986-1990",
  },
  {
    id: "20",
    name: "Dr Gambo T. Yusuf",
    image: "/placeholder.svg?height=200&width=200",
    position: "2nd Vice President",
    activeFrom: "1986-1990",
  },
  {
    id: "20",
    name: "Dr Usman Nakorgi",
    image: "/placeholder.svg?height=200&width=200",
    position: "Sec Gen",
    activeFrom: "1986-1990",
  },
  {
    id: "20",
    name: "Usman B Muhammad",
    image: "/placeholder.svg?height=200&width=200",
    position: "Asst. Sec Gen",
    activeFrom: "1986-1990",
  },
  {
    id: "30",
    name: "Muhammad B Mustapha",
    image: "https://i.ibb.co/mB2dnGH/the-president.jpg",
    position: "Fin. Sec",
    activeFrom: "1986-1990",
  },
  {
    id: "30",
    name: "Abdulkadir Yahttps://i.ibb.co/XtPzmbR/yanda.jpgFin. Sec",
    activeFrom: "1986-1990",
    email: "abusyaventuresltd@gmail.com",
    //phoneNumber: "",
  },
  {
    id: "30",
    name: "Dr Sheikh A. Abdullahi",
    image: "",
    position: "Treasurer",
    activeFrom: "1986-1990",
  },
  {
    id: "30",
    name: "Shehu Abdullahi",
    image: "",
    position: "Asst. Treasurer",
    activeFrom: "1986-1990",
  },
  {
    id: "30",
    name: "Usman B. Ibrahim",
    image: "",
    position: "Sec. Special Duties",
    activeFrom: "1986-1990",
  },
  {
    id: "30",
    name: "Mustapha Ndanusa",
    image: "",
    position: "Social Sec",
    activeFrom: "1986-1990",
  },
  {
    id: "30",
    name: "Lakpene Yusuf",
    image: "",
    position: "Legal Adviser",
    activeFrom: "1986-1990",
  },
  {
    id: "30",
    name: "Baba Alfa",
    image: "https://i.ibb.co/xHL5yd7/baba-alfa-3.jpg",
    position: "P.R.O",
    activeFrom: "1986-1990",
  },
  {
    id: "30",
    name: "Majigi Aliyu",
    image: "",
    position: "Asst P.R.O",
    activeFrom: "1986-1990",
  },
  {
    id: "30",
    name: "Abdullahi A. Adamu",
    image: "",
    position: "Ex Official",
    activeFrom: "1986-1990",
  },
  {
    id: "30",
    name: "Alh Muhammad Salihu",
    image: "",
    position: "Ex Official",
    activeFrom: "1986-1990",
  },
  {
    id: "30",
    name: "Adamu N. Ahmad",
    image: "",
    position: "Ex Official",
    activeFrom: "1986-1990",
  },

  //1990-2006
  {
    id: "18",
    name: "Alfa Muhammad",
    image: "/placeholder.svg?height=200&width=200",
    position: "President",
    activeFrom: "1990-2006",
  },
  {
    id: "19",
    name: "Bako Bawa",
    image: "https://i.ibb.co/HgK0DD9/bako-bawa.jpg",
    position: "1st Vice President",
    activeFrom: "1990-2006",
  },
  {
    id: "20",
    name: "Usman Nakordi",
    image: "/placeholder.svg?height=200&width=200",
    position: "2nd Vice President",
    activeFrom: "1990-2006",
  },
  {
    id: "20",
    name: "Muhammad B. Mustapha",
    image: "https://i.ibb.co/mB2dnGH/the-president.jpg",
    position: "Sec Gen",
    activeFrom: "1990-2006",
  },
  {
    id: "20",
    name: "Muhammad B. Ndamiini",
    image: "/placeholder.svg?height=200&width=200",
    position: "Asst. Sec Gen",
    activeFrom: "1990-2006",
  },
  {
    id: "30",
    name: "Usman B. Muhammad",
    image: "",
    position: "Fin. Sec",
    activeFrom: "1990-2006",
  },
  {
    id: "30",
    name: "Babatsu B. Mustapha",
    image: "",
    position: "Asst Fin. Sec",
    activeFrom: "1990-2006",
  },
  {
    id: "30",
    name: "Baba Alfa",
    image: "https://i.ibb.co/xHL5yd7/baba-alfa-3.jpg",
    position: "Treasurer",
    activeFrom: "1990-2006",
  },
  {
    id: "30",
    name: "Shehu I. Abdullahi",
    image: "",
    position: "Asst. Treasurer",
    activeFrom: "1990-2006",
  },
  {
    id: "30",
    name: "Yahaya Mustapha",
    image: "",
    position: "Sec. Special Duties",
    activeFrom: "1990-2006",
  },
  {
    id: "30",
    name: "Usman Mohammad Alkali",
    image: "",
    position: "Social Sec",
    activeFrom: "1990-2006",
  },
  {
    id: "30",
    name: "Musa B. Abdul",
    image: "",
    position: "Legal Adviser",
    activeFrom: "1990-2006",
  },
  {
    id: "30",
    name: "Muhammad Yakatun Abubakar",
    image: "",
    position: "P.R.O",
    activeFrom: "1990-2006",
  },
  {
    id: "30",
    name: "Abdullahi A. Adamu",
    image: "",
    position: "Ex Official",
    activeFrom: "1990-2006",
  },
  {
    id: "30",
    name: "Abdullahi N. Aliyu",
    image: "",
    position: "Ex Official",
    activeFrom: "1990-2006",
  },
  {
    id: "30",
    name: "Muhammad B. Shehu",
    image: "",
    position: "Ex Official",
    activeFrom: "1990-2006",
  },
  {
    id: "30",
    name: "Baba Aminu Alhaji",
    image: "",
    position: "Ex Official",
    activeFrom: "1990-2006",
  },
  {
    id: "30",
    name: "Dr. Sheikh A. Abdullahi",
    image: "",
    position: "Ex Official",
    activeFrom: "1990-2006",
  },

  //2006-2016
  {
    id: "18",
    name: "Alhaji Usman B. Ibrahim",
    image: "/placeholder.svg?height=200&width=200",
    position: "President",
    activeFrom: "2006-2016",
  },
  {
    id: "19",
    name: "Sulayman Y. Muhammad",
    image: "/placeholder.svg?height=200&width=200",
    position: "1st Vice President",
    activeFrom: "2006-2016",
  },
  {
    id: "20",
    name: "Muhammad B. Shehu",
    image: "/placeholder.svg?height=200&width=200",
    position: "2nd Vice President",
    activeFrom: "2006-2016",
  },
  {
    id: "20",
    name: "Baba Alfa",
    image: "https://i.ibb.co/xHL5yd7/baba-alfa-3.jpg",
    position: "Sec Gen",
    activeFrom: "2006-2016",
  },
  {
    id: "20",
    name: "Abdulkadir Yamma",
    image: "https://i.ibb.co/XtPzmbR/yanda.jpg",
    position: "Asst. Sec Gen",
    activeFrom: "2006-2016",
    email: "abusyaventuresltd@gmail.com",
  },
  {
    id: "30",
    name: "Abdulkadir H. Yahaya",
    image: "",
    position: "Fin. Sec",
    activeFrom: "2006-2016",
  },
  {
    id: "30",
    name: "Mustapha J. Yahaya",
    image: "",
    position: "Asst Fin. Sec",
    activeFrom: "2006-2016",
  },
  {
    id: "30",
    name: "Mohammed Sani",
    image: "",
    position: "Treasurer",
    activeFrom: "2006-2016",
  },
  {
    id: "30",
    name: "Abubakar Gitsu Muhammad",
    image:
      "https://i.ibb.co/QCcrPJQ/Whats-App-Image-2024-10-26-at-20-10-13-bc3bb96b.jpg",
    position: "Asst. Treasurer",
    activeFrom: "2006-2016",
  },
  {
    id: "30",
    name: "Kasim N. Yawa",
    image: "",
    position: "Sec. Special Duties",
    activeFrom: "2006-2016",
  },
  {
    id: "30",
    name: "Alhaji Ndagi Albdulkadir",
    image: "",
    position: "Social Sec",
    activeFrom: "2006-2016",
  },
  {
    id: "30",
    name: "Muhammad Liman",
    image: "",
    position: "Legal Adviser",
    activeFrom: "2006-2016",
  },
  {
    id: "30",
    name: "Abubakar M. Yakatun",
    image: "",
    position: "P.R.O",
    activeFrom: "2006-2016",
  },
  {
    id: "30",
    name: "Abubakar Tanko Suleiman",
    image: "",
    position: "Ex Official",
    activeFrom: "2006-2016",
  },
  {
    id: "30",
    name: "Bako M. Bawa",
    image: "https://i.ibb.co/HgK0DD9/bako-bawa.jpg",
    position: "Ex Official",
    activeFrom: "2006-2016",
  },
  {
    id: "30",
    name: "Muhammad B. Mustapha",
    image: "",
    position: "Ex Official",
    activeFrom: "2006-2016",
  },
  {
    id: "30",
    name: "Mohammed T. Salihu",
    image: "",
    position: "Ex Official",
    activeFrom: "2006-2016",
  },

  //2016-Till Date
  {
    id: "18",
    name: "Muhammad B. Mustapha",
    image: "https://i.ibb.co/mB2dnGH/the-president.jpg",
    position: "President",
    activeFrom: "2016-2024",
    email: "babatifin@gmail.com",
    phoneNumber: "08035882102",
  },
  {
    id: "19",
    name: "Baba Alfa",
    image: "https://i.ibb.co/xHL5yd7/baba-alfa-3.jpg",
    position: "1st Vice President",
    activeFrom: "2016-2024",
    email: "babaalfa21@gmail.com",
    phoneNumber: "08035901914",
  },
  {
    id: "20",
    name: "Justice M.T Salihu (RTD)",
    image: "/placeholder.svg?height=200&width=200",
    position: "2nd Vice President",
    activeFrom: "2016-2024",
    email: "tankosalihu8@gmail.com",
    phoneNumber: "08035975919",
  },
  {
    id: "20",
    name: "Abdulkadir Yamma",
    image: "https://i.ibb.co/XtPzmbR/yanda.jpg",
    position: "Sec Gen",
    activeFrom: "2016-2024",
    email: "abusyaventuresltd@gmail.com",
    phoneNumber: "08036517581",
  },
  {
    id: "20",
    name: "Umar A. Dzukogi",
    image: "https://i.ibb.co/ScTPftf/ass-sec-gen.jpg",
    position: "Asst. Sec Gen",
    activeFrom: "2016-2024",
    email: "umardzukogi@yahoo.com",
    phoneNumber: "08035921260",
  },
  {
    id: "30",
    name: "Gimba Shuaibu",
    image: "https://i.ibb.co/L8bQ0hk/fin-sec.jpg",
    position: "Fin. Sec",
    activeFrom: "2016-2024",
    email: "ndaginasirugimba@gmail.com",
    phoneNumber: "08035907461",
  },
  {
    id: "30",
    name: "Muhammad Yusuf Raji",
    image: "",
    position: "Asst Fin. Sec",
    activeFrom: "2016-2024",
    email: "",
    phoneNumber: "08035917994",
  },
  {
    id: "30",
    name: "Abubakar Gitsu Muhammad",
    image:
      "https://i.ibb.co/QCcrPJQ/Whats-App-Image-2024-10-26-at-20-10-13-bc3bb96b.jpg",
    position: "Treasurer",
    activeFrom: "2016-2024",
    email: "gitsua@gmail.com",
    phoneNumber: "08036493454",
  },
  {
    id: "30",
    name: "Aliyu Macin",
    image: "https://i.ibb.co/n3KFydz/ass-treasurer.jpg",
    position: "Asst. Treasurer",
    activeFrom: "2016-2024",
    email: "",
    phoneNumber: "07035796289",
  },
  {
    id: "30",
    name: "Muhammadu Baba Usman",
    image: "",
    position: "Sec. Special Duties",
    activeFrom: "2016-2024",
    email: "",
    phoneNumber: "07039326309",
  },
  {
    id: "30",
    name: "Alhaji Sani Muhammad",
    image: "",
    position: "Social Sec",
    activeFrom: "2016-2024",
    email: "",
    phoneNumber: "08038456211",
  },
  {
    id: "30",
    name: "Barr. Hadiza Nura Alfa",
    image: "",
    position: "Legal Adviser",
    activeFrom: "2016-2024",
    email: "",
    phoneNumber: "",
  },
  {
    id: "30",
    name: "Abdulmumini Madami (Pele)",
    image: "",
    position: "P.R.O",
    activeFrom: "2016-2024",
    phoneNumber: "08078486702",
  },
  {
    id: "30",
    name: "Prof. M.A.T Suleiman",
    image:
      "https://i.ibb.co/VQWrHpD/Whats-App-Image-2024-10-26-at-20-17-42-530d242b.jpg",
    position: "Ex Official",
    activeFrom: "2016-2024",
    phoneNumber: "08034747754",
  },
  {
    id: "30",
    name: "Bako Muhammad Bawa",
    image: "https://i.ibb.co/HgK0DD9/bako-bawa.jpg",
    position: "Ex Official",
    activeFrom: "2016-2024",
    email: "bakobawa@gmail.com",
    phoneNumber: "08033141460",
  },
  {
    id: "30",
    name: "Usman B. Ibrahim",
    image: "",
    position: "Ex Official",
    activeFrom: "2016-2024",
    email: "",
    phoneNumber: "08036208171",
  },
  {
    id: "30",
    name: "Abubakar Muhammad Yakatun",
    image:
      "https://i.ibb.co/Zh9pWBN/Whats-App-Image-2024-10-26-at-20-19-32-a8b0357b.jpg",
    position: "Ex Official",
    activeFrom: "2016-2024",
    email: "abubakarmohammedyakatun@gmail.com",
    phoneNumber: "08037001954",
  },
];
